.\" Manpage for droopy.
.\" Contact stackp@online.fr to correct errors or typos.
.TH man 1 "21 November 2013" "20131121" "droopy man page"
.SH NAME
droopy \- mini Web server to let others upload files to your computer.
.SH SYNOPSIS
droopy [options] [PORT]
.SH DESCRIPTION
Droopy is a mini Web server whose sole purpose is to let others upload files to your computer.
.TP  5
The default port is 8000.
.SH OPTIONS
.TP  5
\fB\-h, \-\-help\fP
.br
Show help message and exit.
.TP  5
\fB\-d DIRECTORY, \-\-directory DIRECTORY\fP
.br
Set the directory to upload files to.
.TP  5
\fB\-m MESSAGE, \-\-message MESSAGE\fP
.br
Set the message.
.TP  5
\fB\-p PICTURE, \-\-picture PICTURE\fP
.br
Set the picture.
.TP  5
\fB\-\-dl\fP
.br
Provide download links.
.TP  5
\fB\-a USER:PASS, \-\-auth USER:PASS\fP
.br
Set the authentication credentials.
.TP  5
\fB\-\-ssl PEMFILE\fP
.br
Set up https using the certificate file.
.TP  5
\fB\-\-chmod MODE\fP
.br
set the file permissions (octal value).
.TP  5
\fB\-\-save-config\fP
.br
Save options in a configuration file.
.TP  5
\fB\-\-delete-config\fP
.br
Delete the configuration file and exit.
.SH EXAMPLE
droopy \-m "Hi, this is Bob. You can send me a file." \-p avatar.png
.SH AUTHOR
Pierre Duquesne <stackp@online.fr>
